name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Step 3: List files for debugging
    - name: List repository files
      run: ls -R

    # Step 4: Configure AWS CLI
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-west-1

    # Step 5: Sync files to S3
    - name: Deploy to S3
      run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --delete

    # Step 6: Verify files in S3
    - name: Verify files in S3
      run: aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}
